---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-api-cicd
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      type: string
      description: Git repository URL
      default: https://github.com/vinaykumarmakam/test-api.git
    - name: git-revision
      type: string
      description: Git revision to build
      default: main
    - name: image-name
      type: string
      description: Container image name
      default: vinaykumarmakam/test-api
    - name: image-tag
      type: string
      description: Container image tag
      default: latest
    - name: helm-release-name
      type: string
      description: Helm release name
      default: test-api
    - name: helm-namespace
      type: string
      description: Kubernetes namespace
      default: products
  
  workspaces:
    - name: source-code
      description: Workspace for source code
    - name: docker-credentials
      description: Docker registry credentials
  
  tasks:
    # Task 1: Clone repository
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-code
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
    
    # Task 2: Run tests
    - name: run-tests
      runAfter:
        - git-clone
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: pytest
            image: python:3.11-slim
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/bash
              set -e
              pip install -r requirements.txt
              pip install pytest pytest-cov
              pytest tests/ -v --cov=src
      workspaces:
        - name: source
          workspace: source-code
    
    # Task 3: Build and push container image
    - name: build-push-image
      runAfter:
        - run-tests
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: source-code
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-name):$(params.image-tag)
        - name: DOCKERFILE
          value: ./Dockerfile
    
    # Task 4: Update Helm chart version
    - name: update-helm-values
      runAfter:
        - build-push-image
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: image-tag
        steps:
          - name: update-tag
            image: alpine:latest
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              sed -i "s/tag: .*/tag: \"$(params.image-tag)\"/" helm-chart/values.yaml
              cat helm-chart/values.yaml | grep tag
      workspaces:
        - name: source
          workspace: source-code
      params:
        - name: image-tag
          value: $(params.image-tag)
    
    # Task 5: Deploy with Helm
    - name: helm-deploy
      runAfter:
        - update-helm-values
      taskRef:
        name: helm-upgrade
      workspaces:
        - name: source
          workspace: source-code
      params:
        - name: chart-path
          value: ./helm-chart
        - name: release-name
          value: $(params.helm-release-name)
        - name: release-namespace
          value: $(params.helm-namespace)
        - name: values-file
          value: values.yaml

---
# PipelineRun example (triggered manually or by webhook)
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: data-product-run-
  generateName: test-api-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: test-api-cicd
  params:
    - name: git-url
      value: https://github.com/your-org/test-api.git
    - name: git-revision
      value: main
    - name: image-name
      value: your-registry/test-api
    - name: image-tag
      value: $(date +%Y%m%d-%H%M%S)
  workspaces:
    - name: source-code
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: registry-credentials
